# Generated by Django 3.2.7 on 2021-09-15 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_modeling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='function',
            field=models.CharField(max_length=255, verbose_name='Функция'),
        ),
        migrations.AlterField(
            model_name='data',
            name='model',
            field=models.ImageField(upload_to='graphics/', verbose_name='График'),
        ),
    ]
