# Generated by Django 3.2.7 on 2021-09-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_modeling', '0002_auto_20210915_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='model',
            field=models.TextField(),
        ),
    ]
