# Generated by Django 3.2.7 on 2021-09-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_modeling', '0003_alter_data_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='data',
            name='interval',
            field=models.IntegerField(verbose_name='Интервал'),
        ),
        migrations.AlterField(
            model_name='data',
            name='model',
            field=models.ImageField(upload_to='graphs/', verbose_name='График'),
        ),
        migrations.AlterField(
            model_name='data',
            name='step',
            field=models.IntegerField(verbose_name='Шаг'),
        ),
    ]
