# Generated by Django 3.2.7 on 2021-10-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_modeling', '0004_auto_20210916_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='function',
            field=models.CharField(max_length=255, verbose_name='Функция, t'),
        ),
        migrations.AlterField(
            model_name='data',
            name='interval',
            field=models.IntegerField(verbose_name='Интервал, dt(день)'),
        ),
        migrations.AlterField(
            model_name='data',
            name='step',
            field=models.IntegerField(verbose_name='Шаг, dt(час)'),
        ),
    ]
